config/routes.rb
Rails.application.routes.draw do
  # get 'hotels/index'
  # get 'hotels/show'
  # get 'hotels/new'
  # get 'hotels/create'
  # get 'hotels/delete'
  # get 'hotels/destroy'
  # get 'rooms/index'
  # get 'rooms/show'
  # get 'rooms/new'
  # get 'rooms/create'
  # get 'rooms/delete'
  # get 'rooms/destroy'
  # get 'bookings/index'
  # get 'bookings/show'
  # get 'bookings/new'
  # get 'bookings/create'
  # get 'bookings/delete'
  # get 'bookings/destroy'
  devise_for :users
  root to: "pages#home"

  resources :rooms do
    resources :bookings
  end

  resources :hotels do
    resources :rooms, only: [:new, :create]
  end

  get '/pages/dashboard'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  validates :starts_at, presence: true
  validates :ends_at, presence: true

  belongs_to :user
  belongs_to :room
end

app/models/hotel.rb
class Hotel < ApplicationRecord
  validates :name, presence: true
  validates :address, presence: true

  has_many :rooms
  has_many :bookings, through: :rooms, dependent: :destroy
end

app/models/room.rb
class Room < ApplicationRecord
  validates :capacity, numericality: { greater_than: 0 }
  validates :capacity, presence: true
  validates :capacity, numericality: { only_integer: true }
  validates :price_per_night, numericality: { greater_than: 0 }

  has_many :users, through: :bookings
  has_many :bookings, dependent: :destroy
  belongs_to :hotel
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

has_many :bookings
has_many :rooms, through: :bookings

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def index
    @bookings = Booking.all
  end

  def show
    @booking = Booking.new
    @booking = Booking.find(params[:id])
  end

  def new
    @booking = Booking.new
  end

  def create
    @room = Room.find(params[:room_id])
    @booking = Booking.new(booking_params)
    @booking.room = @room
    @booking.user = current_user
    if @booking.save!
      redirect_to room_path(@room), notice: 'Your booking is confirmed.'
    else
      render :new, status: :unprocessable_entity
    end
  end

  def delete
    @booking = Booking.find(params[:id])
  end

  def destroy
    @booking = Booking.find(params[:id])
    @booking.destroy
  end

  private

  def booking_params
    params.require(:booking).permit(:starts_at, :ends_at, :room_id)
  end

end

app/controllers/hotels_controller.rb
class HotelsController < ApplicationController
  def index
    @hotels = Hotel.all
  end

  def show
    @hotel = Hotel.find(params[:id])
  end

  def new
    @hotel = Hotel.new
  end

  def create
    @hotel = Hotel.new(hotel_params)
    if @hotel.save!
      redirect_to _path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def delete
    @hotel = Hotel.find(params[:id])
  end

  def destroy
    @hotel = Hotel.find(params[:id])
    @hotel.destroy
  end

  private

  def hotel_params
    params.require(:hotel).permit(:name, :address)
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home ]

  def home
  end

  def dashboard
    @user = current_user
    @bookings = Booking.where(user_id: current_user.id)
    @rooms = current_user.rooms
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  def index
    @rooms = Room.all
    @hotels = Hotel.all
  end

  def show
    @room = Room.find(params[:id])
    @booking = Booking.new
  end

  def new
    @room = Room.new
  end

  def create
    @hotel = Hotel.find(params[:hotel_id])
    @room = Room.new(room_params)
    @room.hotel = @hotel
    if @room.save!
      redirect_to
    else
      render :new, status: :unprocessable_entity
    end
  end

  def delete
    @room = Room.find(params[:id])
  end

  def destroy
    @room = Room.find(params[:id])
    @room.destroy
  end

  private

  def room_params
    params.require(:room).permit(:price_per_night, :capacity, :hotel_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/create.html.erb
<h1>Bookings#create</h1>
<p>Find me in app/views/bookings/create.html.erb</p>

app/views/bookings/delete.html.erb
<h1>Bookings#delete</h1>
<p>Find me in app/views/bookings/delete.html.erb</p>

app/views/bookings/destroy.html.erb
<h1>Bookings#destroy</h1>
<p>Find me in app/views/bookings/destroy.html.erb</p>

app/views/bookings/index.html.erb
<h1>Bookings#index</h1>
<p>Find me in app/views/bookings/index.html.erb</p>

app/views/bookings/new.html.erb
<h1>Bookings#new</h1>
<p>Find me in app/views/bookings/new.html.erb</p>

app/views/bookings/show.html.erb
<h1>Bookings#show</h1>
<p>Find me in app/views/bookings/show.html.erb</p>

app/views/hotels/create.html.erb
<h1>Hotels#create</h1>
<p>Find me in app/views/hotels/create.html.erb</p>

app/views/hotels/delete.html.erb
<h1>Hotels#delete</h1>
<p>Find me in app/views/hotels/delete.html.erb</p>

app/views/hotels/destroy.html.erb
<h1>Hotels#destroy</h1>
<p>Find me in app/views/hotels/destroy.html.erb</p>

app/views/hotels/index.html.erb
<h1>Hotels#index</h1>
<p>Find me in app/views/hotels/index.html.erb</p>

app/views/hotels/new.html.erb
<h1>Hotels#new</h1>
<p>Find me in app/views/hotels/new.html.erb</p>

app/views/hotels/show.html.erb
<h1>Hotels#show</h1>
<p>Find me in app/views/hotels/show.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsBookRoomsChallenge</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css">

    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Open+Sans:ital,wght@0,300;0,400;0,500;0,600;0,700;1,300;1,400;1,500;1,600&display=swap" rel="stylesheet">

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">
  </head>

  <body>
    <%= render "shared/navbar" %>
    <%= render "shared/flashes" %>

    <%= yield %>
  </body>
</html>

app/views/pages/dashboard.html.erb
<div class="container">
  <h1>My Bookings</h1>
  <hr>
  <div class="cards">
  <% @bookings.each do |booking| %>
  <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://images.pexels.com/photos/164595/pexels-photo-164595.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2)">
    <%# <%= link_to image_tag("https://img.icons8.com/?size=512&id=99933&format=png"), room_booking(@booking.room), data: { turbo_method: :delete, turbo_confirm: "Are you sure you want to delete this room?"} %>
    <div class="description">
    <%= booking.room.hotel.name %>
      <div class="number">
        <p>Room n°<%=booking.room.id%></p>
      </div>
      </div>
  </div>
<% end %>
</div>
</div>

app/views/pages/home.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://images.pexels.com/photos/258154/pexels-photo-258154.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2);">
  <div class="d-flex justify-content-center align-items-center home-content">
      <div class="container">
        <h1 class="maintitle">SolBnb</h1>
        <button class="button-40" role="button"><%= link_to "Discover our rooms", rooms_path, style: "color: white;", class: "no-underline"%></button>
      </div>

  </div>
</div>

app/views/rooms/_booking_form.html.erb
<div class="">
  <div class="row">
    <div class="">
      <div class="bg-white p-3 shadow" style="border-radius: 10px">
        <div class ="border-radius">
          <h3> <strong> Book a Room </strong></h3>
          <%= simple_form_for [@room, @booking], data: { controller: 'dater', dater_price_value: @room.price_per_night } do |f| %>
            <strong><%= "#{@room.price_per_night}""€ "%></strong><%="per night"%>
            <div class="mt-4">
              <span style="font-size: 14px"><strong><%= f.input :starts_at, input_html: {data: { controller: 'datepicker', dater_target: "startDate"}, placeholder: "Click to select a date" }, as: :string, style: "border:none border-radius: 25px" %></strong>
              <span style="font-size: 14px"><strong><%= f.input :ends_at, input_html: {data: { controller: 'datepicker',  dater_target: "endDate"}, placeholder:"Click to select a date" }, as: :string %></strong>
              <hr>
              <%# <span style="font-size: 14px; border: none"><strong><%= p (f.input :total_amount, disabled: true, readonly: true, input_html: { data: { dater_target: "totalAmount" } }, class: 'custom-input') %></strong>
              <%=  f.submit class: 'btn btn-primary color-D7572B' %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/rooms/create.html.erb
<h1>Rooms#create</h1>
<p>Find me in app/views/rooms/create.html.erb</p>

app/views/rooms/delete.html.erb
<h1>Rooms#delete</h1>
<p>Find me in app/views/rooms/delete.html.erb</p>

app/views/rooms/destroy.html.erb
<h1>Rooms#destroy</h1>
<p>Find me in app/views/rooms/destroy.html.erb</p>

app/views/rooms/index.html.erb
<div class="container">
<h1>Our Rooms</h1>
<hr>
<div class="cards">
<% @rooms.each do |room| %>
  <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://images.pexels.com/photos/164595/pexels-photo-164595.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2)">
    <div class="description">
      <div class="text">
        <%= link_to room.hotel.name, room_path(room), style: "color: white;", class: "no-underline" %>
      </div>
      <div class="number">
        <p>Room n°<%=room.id%></p>
      </div>
      </div>
  </div>
<% end %>
</div>
</div>

app/views/rooms/new.html.erb
<h1>Rooms#new</h1>
<p>Find me in app/views/rooms/new.html.erb</p>

app/views/rooms/show.html.erb
<div class="container">
<h1 class= "hotel-title">Room details</h1>
<hr>
  <div class="d-flex w-100 justify-content gap-5">
    <div class="w-50 d-flex flex-column justify-content-between" style="border-radius: 20px">
    <%= image_tag("https://images.pexels.com/photos/164595/pexels-photo-164595.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2", class: "img-booking") %>
    <hr>
    </div>
    <div class="w-50">
      <%= render "booking_form", booking: @booking, data: {turbo_confirm: "Are you sure?"} %>
    </div>
  </div>
  <strong><h2><%= @room.hotel.name %></h2></strong>
   <p><i class="fa-solid fa-user"></i> <%= @room.capacity %>  people </p>

  <button class="button-40" role="button"><%= link_to "Back", rooms_path, style: "color: white;", class: "no-underline"%></button>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to root_path, class: "navbar-brand" do %>
      <%= image_tag "https://static.vecteezy.com/system/resources/previews/011/097/543/original/bed-icon-design-simple-interior-and-furniture-illustration-png.png" %>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to "All Rooms", rooms_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "My Bookings", pages_dashboard_path, class: "nav-link" %>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>